---
- name: Implement closed loop automation with Ansible and ServiceNow
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/servicenow-credentials.yml

  tasks:
    - name: Create ServiceNow Change Request
      servicenow.itsm.change_request:
        instance:
          host: "https://{{ SN_INSTANCE }}.service-now.com"
          username: "{{ SN_USERNAME }}"
          password: "{{ SN_PASSWORD }}"
        type: standard
        state: new
        short_description: Hello World Change Request
        description: Hello World Change Request
      register: new_change_request

    - name: Show Change Request details
      ansible.builtin.debug:
        var: new_change_request

    # - name: Store Change Request number as artifact for later in the workflow
    #   template:
    #     src: ./templates/snow-change-request.j2
    #     dest: "{{ working_dir }}/snow-change-request.yml"
    #   run_once: yes
    #   delegate_to: localhost
    #   when: from_snow|bool
    #
    # - name: Print out Change Request number
    #   debug:
    #     msg: "The newly created Change Request is {{ new_change_request.record.number }}. Awaiting Approval."
    #   when: from_snow|bool
    #
    # #https://www.infinitypp.com/ansible/email-notifications-with-examples/
    # - name: Sending an email requesting approval
    #   mail:
    #     host: smtp.gmail.com
    #     port: 587
    #     username: "{{ gmail_username }}"
    #     password: "{{ gmail_password }}"
    #     to:
    #     - "Michael Ford <{{ approver_email }}>"
    #     - "{{secondary_approver}}"
    #     #- "{{tertiary_approver}}"
    #     subject: "Approval request for ServiceNow Change Request {{ new_change_request.record.number }}"
    #     body: "You have a new CR Approval request. Please click on this URL to approve: https://{{ SNOW_INSTANCE }}.service-now.com/nav_to.do?uri=change_request.do?sysparm_query=number={{ new_change_request.record.number }}"
    #   delegate_to: localhost
    #   when: from_snow|bool
    #
    # - name: Wait for Change Request approval
    #   snow_record_find:
    #     username: "{{ SNOW_USERNAME }}"
    #     password: "{{ SNOW_PASSWORD }}"
    #     instance: "{{ SNOW_INSTANCE }}"
    #     table: change_request
    #     query:
    #       AND:
    #         equals:
    #           number: "{{ new_change_request.record.number }}"
    #   register: change_request_status
    #   when: from_snow|bool
    #   until: change_request_status.record[0].state == "-2"
    #   retries: 50
    #   delay: 10
    #
    # - debug:
    #     msg: "Change Request {{ new_change_request.record.number }} has been approved!"
    #   when: from_snow|bool
    #
    # - name: Close the ServiceNow Change Request
    #   servicenow.itsm.change_request:
    #     instance:
    #       host: "https://{{ SNOW_INSTANCE }}.service-now.com"
    #       username: "{{ SNOW_USERNAME }}"
    #       password: "{{ SNOW_PASSWORD }}"
    #     type: standard
    #     close_code: "successful"
    #     close_notes: "Closed"
    #
    #   register: new_change_request
    #   when: from_snow|bool



    #state
    # -5 is just created
    # -4 means approval has been requested
    # -3 means partial approval
    # -2 means it has been approved
    # -1 means it is in the implement stage
    # 0 means it is in the review state
    # 3 means CR closed successfully (perhaps with issues)

    #approval
    # - not requested
    # - requested
    # - approved

    #close_code
    # - successful
    # - successful with issues
    # - unsuccessful

    #closed_notes
